### ISSUE TITLE
Missing versioning

### ISSUE THREAD

**Issue by nenadalm** [fishman/ctags#228]
I see no versioning here. What is current version, what commit it is, what's the previous version...

I think git tags could be used for versioning? And every commit inside master should increase version? So if somebody decides to create release for his platform he knows what version to specify?

(no need to mark older releases I think, just mark current HEAD as some version and tag every other commit with new version)

Inside output of ``make -f maintainer.mak help-release`` I see version consists of 2 numbers. So it would be also helpfull to provide docs what do they mean.
(something like summary of semver http://semver.org/ would be enough)

**Comment by b4n** [comment]
> I see no versioning here.

Indeed, ctags --version doesn't seem to say anything about it.  But we have #222 on the way, (though not ready yet)

> I think git tags could be used for versioning?

Yes, I imagine we'll use Git tag to tag releases.

> And every commit inside master should increase version?

*every* commit??  No I don't think so.  master is not a stable release, it is the development tree, there is no point in tagging each commit.  If really people want to make releases from something else than a release, they can always suffix the current version number with the commit SHA.

> I see version consists of 2 numbers. So it would be also helpfull to provide docs what do they mean.

May be nice, but as CTags is a program I don't think it matters so much -- especially as I believe the current version is more "major changes"."minor changes" than anything else.  Sure I like the semver style [1], but OTOH many people don't like when programs are versioned like `0.9458.2` and would rather see `12.5` or something.  Apparently there are even studies that show people are more confident in programs with high major version numbers, because it unconsciously give a sort of active/stable quality.
And if a program like ctags were to use semver-like versioning, I guess/hope we'd be stuck to v5.x.y forever :)

[1] though for library versioning there are more meaningful conventions to address the compatibility issue, like e.g. Libtool versioning scheme -- but that's not even the *package's* version, but the library API one.

**Comment by nenadalm** [comment]
Ok, thanks for clarifying. Only reason why I thought to tag every commit in master was that you can build any commit and release it. But if commit is appended to versions as described inside of the PR it's fine.

**Comment by masatake** [comment]
I thinks solving #222 is very basic step for other releasing related make targets.
