### ISSUE TITLE
C parser #if 0 code

### ISSUE THREAD

**Issue by jonthn** [fishman/ctags#320]
While trying to parse a project I came across something strange, even though the code is protected by a ```#if 0``` ctags parse this code but it shouldn't.
And I get this assertion: 
```
Assertion failed: (Cpp.ungetch2 == '\0'), function cppUngetc, file main/get.c, line 170
```
see https://github.com/fishman/ctags/blob/master/main/get.c#L170

If I use ```--if0=yes``` it seems to take the right path.

### Example code
```C
#if 0
/* example of code non valid but the programmer should enter correct value here */
functionA(constant_????,  constant_?????, NULL);
#else
functionA(1, 2, NULL);
#endif
```

**Comment by b4n** [comment]
> even though the code is protected by a `#if 0` ctags parse this code but it shouldn't.

It should parse it to understand the syntax relevant to decide on the branches to take or not to take.

But indeed there is a but with your example triggering an assertion failure.

----
PS: you probably shouldn't be using the preprocessor as a way to comment things, they are not the same.  Also beware sequences of `??` because of C trigraphs, they could result in some very unexpected things ;)
```C
#if 0
//nothing??/
#else
#error or not
#endif
```

**Comment by jonthn** [comment]
My thoughts exactly wrong choice of word my bad.

Unfortunately it's not under my control for this code, it's rather ancient and I have to live with it ... :(

**Comment by b4n** [comment]
Okay, the reason why this happens is because `cppGetc()` calls `cppUngetc()` when it encounters an unknown trigraph, and as it keeps on looping when it's in an ignored branch, it keeps on stacking characters in the ungetc buffer  -- but never reads them.

So to reproduce, you just need
```C
#if 0
??????
```
and BTW, it also happens with backslash-escaped question marks:
```C
#if 0
\?\?\?
```

For the moment I'm not sure of the implications of changing those `cppUngetc()` calls, but I might get a look at this later if nobody beats me to it :)

BTW, we miss trigraph unit tests, so writing some would be where to start to be sure not to break something here.

**Comment by masatake** [comment]
@b4n, who will beat you? Of course your the best person:-)

**Comment by b4n** [comment]
OK, the fix was a bit more complex than one could have hoped, but here it is in #325
